### ISSUE TITLE
Flood of process

### ISSUE THREAD

**Issue by rleite** [jkphl/iconizr#29]
Hi!

For some time we started to use iconizr(grunt-iconizr) to create sprices of svg and a sprite fallback of pngs(thanks btw).

The problem is that now we have 182 svgs and all of them are launching independent process to convert them to png. This created a fooding of process.

Can this be done with a parallel limit approach? I'm thinking of NUMBER_OF_CPUS * 2.

**Comment by jkphl** [comment]
Hi @rleite,

the issue has been addressed [here](https://github.com/jkphl/node-iconizr/pull/11).

Cheers,
Joschi
