### ISSUE TITLE
Icons come out broken

### ISSUE THREAD

**Issue by Wolfr** [jkphl/iconizr#30]
http://cl.ly/image/383J1K1o2G1r

Are there certain SVG features iconizr doesn't support? Some of my exports come out fine and some are broken (bounding box wrong; or subtract shapes is not applied)

Thank you

**Comment by jkphl** [comment]
Hi @Wolfr,

iconizr itself doesn't "support" any SVG feature — it just compiles a sprite and renders PNG fallbacks out of your SVG source files. What is more likely to cause your troubles is [SVGO](https://github.com/svg/svgo), which is probably what you implicitly use for optimizing (and thus altering) your SVGs? SVGO is known for having some pretty aggressive plugins, which are not compatible with particular SVGs. There is no way of predicting which plugin is safe to use with which SVG. You should try to disable some of these plugins to find out which one is evil in your situation.

Unfortunately, the PHP version of iconizr doesn't support configuring the SVGO plugins being enabled. If you have the chance, switch to the [Node.js based iconizr](https://github.com/jkphl/node-iconizr) or it's [Grunt plugin](https://github.com/jkphl/grunt-iconizr), which both allow configuring SVGO via the `cleanconfig` option (please see the [available options](https://github.com/jkphl/svg-sprite/tree/bbd051e940e7b6373ed56277251a8affb03b1c10#available-options) for some hints).

At the time of this writing, a completely rewritten version of *iconizr* is on it's way, based on the latest release of [svg-sprite](https://github.com/jkphl/svg-sprite), and there will be a Gulp plugin soon as well.

Hope this helps! Cheers,
Joschi
