### ISSUE TITLE
Calling svgo

### ISSUE THREAD

**Issue by oschrenk** [jkphl/iconizr#32]
The documentation mentions compatibility with svgo. But `iconizr --help`  just offers 

```
--scour <string>           Absolute path to scour script for cleaning SVG files (see http://www.codedread.com/scour)
```

How do I use svgo?

**Comment by jkphl** [comment]
Hi @oschrenk,

*iconizr* checks for the availability of an `svgo` binary on your system (by calling `which svgo` — please note that this might only work on Linux / OS X platforms). A regular SVGO installation should register this binary on your system. *iconizr* will automatically try to use SVGO in case you didn't specify a `--scour` option for your command.

By the way: The PHP version of *iconizr* is totally outdated (and I'm not decided if I'll ever work on it again). As soon as you install SVGO, which is a Node.js module, you should definitely consider switching to the [Node.js iconizr module](https://github.com/jkphl/node-iconizr), which has a lot more features and is still kinda maintained (there's a new generation available in the [dev branch](https://github.com/jkphl/node-iconizr/tree/dev) that I'm trying to finish for quite some time now). 

Good luck & cheers,
Joschi
