### ISSUE TITLE
Animated pseudo effects?

### ISSUE THREAD

**Issue by joelataylor** [jkphl/iconizr#33]
Hi guys, I'm sure you've thought about how to achieve pseudo effects that could animate a property of the SVG - rather than a full replacement graphic.

This would require embedding the svg into the html, and some css declaration of said transition. So is probably out-of-scope for the project. But I'm still curious as to what type of thoughts/ideas you have for this?

Thx!

**Comment by jkphl** [comment]
hey @joelataylor,

well, you're pretty much answering the question yourself: Stuff like this is definitely out of the scope of *iconizr*. ;)

*iconizr*'s primary purpose **is to provide full replacements** (i.e. PNG fallbacks) for clients that don't support SVG. Another side effect is that *iconizr* creates SVG sprites for you. You wouldn't need a tool like this to do these animation effects you're talking about (and in fact I can't imagine how a tool could help you with that at all). You're right, you will have to embed the SVG inline into your HTML document, and you will need to specify the animations manually. 

You might have noticed that this (PHP-based) version of *iconizr* is pretty outdated and unmaintained. You should have a look at [svg-sprite](https://github.com/jkphl/svg-sprite/), which is the base of the [Node-based iconizr version](https://github.com/jkphl/node-iconizr/). *svg-sprite* has lots of additional features, e.g. support for inline SVG sprites. I'm considering adding features for dynamically embedding the SVGs into HTML source for quite a while now, but so far I'm just lacking the time for that.

Hope this helped a little.

Cheers, Joschi
