### ISSUE TITLE
Web version fails when your SVG has a "fill"

### ISSUE THREAD

**Issue by cyphix333** [jkphl/iconizr#36]
I have been testing this tool out and it has worked fine until now; I had been using SVG's without a "fill"; but I wanted the icons to be blue. so I added a fill to my SVG icons I loaded in, such as:

 `<svg fill="##34495e" ...>`

...but it seemed to choke on this; whilst it gave me all the folders, the only folder that had anything in it was the _css/icons_ folder, which contained all the separate .svg icons. No .css files, no .scss files and no .png files which I requested.

**Comment by cyphix333** [comment]
False alarm. I did a mass search/replace on the files to add the fill, but seems a couple of the files it did a replacement in another area where it shouldn't have and hence I guess the tool choked on these files.

Whilst it doesn't have an issue with fill, it would be nice if it reported an error rather than appearing like it was successful. :)

**Comment by jkphl** [comment]
@cyphix333 Glad you could figure this out.

Please be aware that iconizr is pretty agnostic towards the content of your SVG files. It's neither able to validate the SVG files in any way, nor does it perform any manipulation (it's "just" SVGO as a third party  tool doing some optimization, and this is probably the part that is failing).

Also, please be aware that the PHP version of iconizr (and the web version which is based on that) is pretty outdated and right now I doubt I will ever improve it again (at least on a PHP basis). In case you're a Node guy you might check out the Node module instead (please refer to the [dev branch](https://github.com/jkphl/node-iconizr/tree/dev)).
