### ISSUE TITLE
Negative countdown

### ISSUE THREAD

**Issue by fremail** [jkphl/iconizr#39]
I set up everything for job. It said me to be patient since 2 jobs in queue.
After several sec the page was updated and it started to count negative seconds. It updated the page and counted negative seconds about 4 or 5 times before it returned me the result archive.

https://www.screencast.com/t/NbksjYDZxX

**Comment by jkphl** [comment]
@fremail Thanks for posting this issue. One question: Did you get your icons in the end, despite the negative countdown?

Just to let you know, this project has been inactive for a very long time and i don't currently plan to pick up development again. I already know about situations where the countdown goes negative, but that's not a problem of the iconizr library itself but rather of the website around it. So, as long as the icon kits are still created, this seems to be a minor glitch only and I probably won't put effort into it. Thanks for your understanding!

**Comment by fremail** [comment]
@jkphl Yes, I got my icons in the end. 

I agree, this issue is minor, so no problem
